spring.datasource.url=jdbc:postgresql://ep-steep-wind-ageod5jo-pooler.c-2.eu-central-1.aws.neon.tech/neondb?sslmode=require&connectTimeout=60
spring.datasource.username=neondb_owner
spring.datasource.password=npg_8fsbkyCQ9Azr
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.hikari.connection-timeout=120000
spring.datasource.hikari.initialization-fail-timeout=-1

server.forward-headers-strategy=framework

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.hibernate.ddl-auto=validate

logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE

sentry.dsn=https://175df70cc551efc22dd25f4cc4c17ef7@o4508285839605760.ingest.de.sentry.io/4508691883622480
sentry.environment=local

asa.care.product.code=CA
asa.paid.care.mission.codes=CA-TEAMBUILDING
SENSITIVE_WORKERS_CODES=W-059,W-00
aws.s3.bucket=dummy-bucket
aws.eventBridge.bus=dummy-event-bus
ACCOUNTANTS=dummy@test.com
MAX_LATENESS_REPORT=4
ASA_CONTRACT_ALERT_THRESHOLD=10

casdoor.logout.url=https://casdoor-2jez.onrender.com/api/logout
asa.logout.url=https://3k2lfme2qlnft4v3ji3hn2o2hm0buvtp.lambda-url.eu-west-3.on.aws/

spring.security.oauth2.client.registration.casdoor.clientid=87420033c3e468e9d0fd
spring.security.oauth2.client.registration.casdoor.client-secret=ef1fc817ca5b9bac1486ed2e6571f504bc1a5b88
spring.security.oauth2.client.registration.casdoor.provider=casdoor
spring.security.oauth2.client.registration.casdoor.redirect-uri={baseUrl}/login/oauth2/code/casdoor
spring.security.oauth2.client.registration.casdoor.authorization-grant-type=authorization_code
spring.security.oauth2.client.registration.casdoor.scope=openid,profile,email
spring.security.oauth2.client.provider.casdoor.issuer-uri=https://casdoor-2jez.onrender.com
spring.security.oauth2.client.provider.casdoor.authorization-uri=https://casdoor-2jez.onrender.com/login/oauth/authorize
spring.security.oauth2.client.provider.casdoor.token-uri=https://casdoor-2jez.onrender.com/api/login/oauth/access_token
spring.security.oauth2.client.provider.casdoor.user-info-uri=https://casdoor-2jez.onrender.com/api/userinfo
spring.security.oauth2.client.provider.casdoor.jwk-set-uri=https://casdoor-2jez.onrender.com/.well-known/jwks
spring.security.oauth2.client.provider.casdoor.user-name-attribute=sub