ALTER TABLE worker
    ADD COLUMN IF NOT EXISTS fullname VARCHAR;

ALTER TABLE worker
    ADD COLUMN IF NOT EXISTS address VARCHAR;

ALTER TABLE worker
    ADD COLUMN IF NOT EXISTS city VARCHAR;

ALTER TABLE worker
    ADD COLUMN IF NOT EXISTS nif VARCHAR;

ALTER TABLE worker
    ADD COLUMN IF NOT EXISTS stat VARCHAR;
